- id: '1618463849231'
  alias: Hall Nightlight On (on motion)
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_motion_occupancy
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.hall_nightlight
    data: {}
  mode: single
- id: '1618464005107'
  alias: Hall Nightlight Off (no motion)
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_motion_occupancy
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.hall_nightlight
  mode: single
- id: '1618550929949'
  alias: Hall Light On (when wardrobe opens)
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_wardrobe_contact
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.hall_light
    data:
      brightness: 255
  mode: single
- id: '1618550971408'
  alias: Hall Light Off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_wardrobe_contact
    to: 'off'
  condition: []
  action:
  - service: light.turn_on
    target:
      entity_id: light.hall_nightlight
  mode: single
- id: '1618773541412'
  alias: Hall Light Off (from unavailable to on, when wardrobe closed)
  description: ''
  trigger:
  - platform: state
    entity_id: light.hall_light
    from: unavailable
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.hall_wardrobe_contact
    state: 'off'
  action:
  - service: light.turn_off
    target:
      entity_id: light.hall_light
  mode: single
- id: '1618773983441'
  alias: Hall Nightlight Off (from unavailable to on, when no motion)
  description: ''
  trigger:
  - platform: state
    entity_id: light.hall_nightlight
    from: unavailable
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.hall_motion_occupancy
    state: 'off'
  action:
  - service: light.turn_off
    target:
      entity_id: light.hall_nightlight
  mode: single
- id: '1619594288367'
  alias: Bedroom Nightlight Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_wallswitch_click
    to: left
  - platform: state
    entity_id: sensor.bedroom_button_click
    to: single
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.bedroom_nightlight
  mode: single
- id: '1619594366583'
  alias: Bedroom Daylight Toggle
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_wallswitch_click
    to: right
  - platform: state
    entity_id: sensor.bedroom_button_click
    to: long
  condition: []
  action:
  - service: light.toggle
    target:
      entity_id: light.bedroom_daylight
  mode: single
- id: '1619615166546'
  alias: Kitchen Light On
  description: ''
  trigger:
  - platform: state
    entity_id: group.kitchen_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.kidsroom_curtain_contact
    state: 'on'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.kitchen_light
  mode: single
- id: '1619615544766'
  alias: Kitchen Light Off
  description: ''
  trigger:
  - platform: state
    entity_id: group.kitchen_motion
    to: 'off'
    for: 00:03:00
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.kitchen_light
  mode: single
- id: '1622739585580'
  alias: Server Turn On
  description: ''
  trigger:
  - platform: time
    at: 00:30:00
  - platform: state
    entity_id: media_player.livingroom_tv
    to: 'on'
  - platform: state
    entity_id: media_player.kitchen_tv
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.server
    state: 'off'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.server
  mode: single
- id: '1622740057760'
  alias: Server Turn Off (at night)
  description: ''
  trigger:
  - platform: time
    at: 05:30:00
  condition:
  - condition: template
    value_template: '{{ states("media_player.livingroom_tv") != "on" }}'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.server
  mode: single
- id: '1623578775596'
  alias: Server turn Off (after 15 min after TV off)
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.livingroom_tv
    from: 'on'
    to: 'off'
    for: 00:15:00
  - platform: state
    entity_id: media_player.kitchen_tv
    to: 'off'
    for: 00:15:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: media_player.kitchen_tv
      state: 'off'
    - condition: state
      entity_id: media_player.livingroom_tv
      state: 'off'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.server
  mode: single
- id: '1623586974424'
  alias: Livingroom TV open Plex (when server on)
  description: ''
  trigger:
  - platform: state
    entity_id: switch.server
    to: 'on'
  condition:
  - condition: template
    value_template: '{{ states("sensor.livingroom_tv_source") != "Apple TV" }}'
  action:
  - service: media_player.select_source
    target:
      entity_id: media_player.livingroom_tv
    data:
      source: Plex
  mode: single
- id: '1626115480591'
  alias: Livingroom Ambilight
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.livingroom_tv_source
  condition: []
  action:
  - service: script.livingroom_ceiling_light_ambilight
    data_template:
      effect: '{{ trigger.to_state.state }}'
  mode: single
- id: '1626116224631'
  alias: Liveingroom Ambilight Plex Pause/Idle
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_lg_lg_oled55b7v_z
    from: playing
    to: paused
  - platform: state
    entity_id: media_player.plex_plex_for_lg_lg_oled55b7v_z
    from: playing
    to: idle
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.livingroom_nightlight
      state: 'on'
    - condition: state
      entity_id: light.livingroom_ambilight
      state: 'on'
  action:
  - service: light.turn_on
    data:
      transition: 5
      brightness_pct: 35
    target:
      entity_id: light.livingroom_nightlight
  mode: single
- id: '1626116489348'
  alias: Liveingroom Ambilight Plex Play
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_lg_lg_oled55b7v_z
    to: playing
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.livingroom_nightlight
      state: 'on'
    - condition: state
      entity_id: light.livingroom_ambilight
      state: 'on'
  action:
  - service: script.livingroom_ceiling_light_ambilight
    data_template:
      effect: '{{ states(''sensor.livingroom_tv_source'') }}'
  mode: single
