
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit:
  advertise_ip: "10.0.1.62"
  filter:
    include_entities:
      - light.livingroom_light
      - light.livingroom_nightlight
      - light.livingroom_ambilight
      - cover.livingroom_curtain
      - script.kitchen_tv_youtube_kids
      - light.bedroom_daylight
      - light.bedroom_nightlight
  entity_config:
    light.livingroom_light:
      name: Свет
    light.livingroom_nightlight:
      name: Ночник
    light.livingroom_ambilight:
      name: Подсветка
    cover.livingroom_curtain:
      name: Шторы
    script.kitchen_tv_youtube_kids:
      name: YouTube Детям
    light.bedroom_daylight:
      name: Свет
    light.bedroom_nightlight:
      name: Ночник

yandex_smart_home:
  notifier:
    - oauth_token: !secret yandex_smart_home_oauth_token
      skill_id: !secret yandex_smart_home_skill_id
      user_id: !secret yandex_smart_home_user_id
  filter:
    include_entities:
      - media_player.livingroom_tv
      - light.livingroom_light
      - light.livingroom_nightlight
      - switch.livingroom_wallswitch_right
      - cover.livingroom_curtain
      - sensor.kidsroom_sensor_temperature
      - switch.server
  entity_config:
    media_player.livingroom_tv:
      name: Телевизор
      room: Гостиная
    light.livingroom_light:
      name: Свет
      room: Гостиная
    light.livingroom_nightlight:
      name: Ночник
      room: Гостиная
    switch.livingroom_wallswitch_right:
      name: Светильники
      room: Гостиная
    cover.livingroom_curtain:
      name: Шторы
      room: Гостиная
    sensor.kidsroom_sensor_temperature:
      room: Детская
    switch.server:
      name: Сервер
      room: Гостиная