
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit:
  advertise_ip: "10.0.1.62"
  filter:
    include_entities:
      - cover.livingroom_curtain
      - light.livingroom_ceiling_light
      - light.livingroom_nightlight
      - light.livingroom_ambilight
      - light.bedroom_daylight
      - light.bedroom_nightlight
      - script.kitchen_tv_youtube_kids
  entity_config:
    light.livingroom_ceiling_light:
      name: Свет
    light.livingroom_nightlight:
      name: Ночник
    light.livingroom_ambilight:
      name: Подсветка
    cover.livingroom_curtain:
      name: Шторы
    script.kitchen_tv_youtube_kids:
      name: YouTube Детям
    light.bedroom_daylight:
      name: Свет
    light.bedroom_nightlight:
      name: Ночник

yandex_smart_home:
  notifier:
    - oauth_token: !secret yandex_smart_home_oauth_token
      skill_id: !secret yandex_smart_home_skill_id
      user_id: !secret yandex_smart_home_user_id
  filter:
    include_entities:
      - cover.livingroom_curtain
      - light.livingroom_ceiling_light
      - light.livingroom_nightlight
      - light.livingroom_ambilight
      - media_player.livingroom_tv_universal
      - media_player.kitchen_tv_universal
      - sensor.kidsroom_sensor_temperature
      - switch.livingroom_wallswitch_right
      - switch.server
      - vacuum.valetudo
  entity_config:
    media_player.livingroom_tv_universal:
      name: Телевизор
      room: Гостиная
      modes:
        input_source:
          one: [Plex]
          two: [YouTube]
      custom_modes:
        input_source:
          state_attribute: source
          set_mode:
            service: media_player.select_source
            entity_id: media_player.livingroom_tv
            data:
              source: '{{ mode }}'
    light.livingroom_ceiling_light:
      name: Свет
      room: Гостиная
    light.livingroom_nightlight:
      name: Ночник
      room: Гостиная
    light.livingroom_ambilight:
      name: Подсветка
      room: Гостиная
    switch.livingroom_wallswitch_right:
      name: Светильники
      room: Гостиная
    cover.livingroom_curtain:
      name: Шторы
      room: Гостиная
    sensor.kidsroom_sensor_temperature:
      room: Детская
    switch.server:
      name: Сервер
      room: Гостиная
    media_player.kitchen_tv_universal:
      name: Телевизор
      room: Кухня
    vacuum.valetudo:
      name: Пылесос
      room: Гостиная