wake_on_lan:

webostv:
  host: 10.0.2.162
  name: livingroom_tv
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webost_tv_mac
      broadcast_address: 10.0.2.162
  customize:
    sources:
      - Plex
      - YouTube
      - Apple TV

sensor:
  - platform: template
    sensors:
      livingroom_tv_source:
        friendly_name: "Источник для телевизора в гостиной"
        value_template: "{{ state_attr('media_player.livingroom_tv', 'source') }}"
