wake_on_lan:

webostv:
  host: 10.0.2.162
  name: livingroom_tv
  turn_on_action:
    service: shell_command.livingroom_tv_wakeup
  customize:
    sources:
      - Plex
      - YouTube
      - Apple TV

media_player:
  - platform: universal
    name: livingroom_tv_universal
    children:
      - media_player.livingroom_tv
    commands:
      media_play:
        service: script.turn_on
        target:
          entity_id: script.livingroom_tv_play
    device_class: tv
    attributes:
      state: media_player.livingroom_tv

sensor:
  - platform: template
    sensors:
      livingroom_tv_source:
        friendly_name: "Источник для телевизора в гостиной"
        value_template: "{{ state_attr('media_player.livingroom_tv', 'source') }}"
  - platform: template
    sensors:
      webost_tv_mac:
        value_template: !secret webost_tv_mac

shell_command:
  livingroom_tv_wakeup: 'ether-wake -i eth0.2 {{ states("sensor.webost_tv_mac") }}'